apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: csi-do-test-pvc-ea0befb9-026c-430d-84ee-1876a50e0426
  namespace: default
spec:
  snapshotClassName: do-block-storage
  snapshotContentName: ""
  source:
    kind: PersistentVolumeClaim
    name: csi-do-test-pvc
status:
  creationTime: null
  error:
    message: 'Failed to create snapshot: the PVC csi-do-test-pvc is not yet bound
      to a PV, will not attempt to take a snapshot'
    time: "2019-02-26T06:25:20Z"
  ready: false
  restoreSize: null
