apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: csi-do-test-pvc-7529b14b-104c-49ef-90e0-014e04589768
  namespace: default
spec:
  snapshotClassName: do-block-storage
  snapshotContentName: ""
  source:
    kind: PersistentVolumeClaim
    name: csi-do-test-pvc
status:
  creationTime: null
  error:
    message: 'Failed to create snapshot: the PVC csi-do-test-pvc is not yet bound
      to a PV, will not attempt to take a snapshot'
    time: "2019-02-26T06:23:20Z"
  ready: false
  restoreSize: null
